version: "2"
services:
  web:
    container_name: app
    restart: unless-stopped
    build: .
    image: flexwebclient_web:latest
    environment:
      - REACT_APP_ADRESS= ${REACT_APP_ADRESS}
      - CI_REGISTRY= ${CI_REGISTRY}
      - CI_REGISTRY_IMAGE= ${CI_REGISTRY_IMAGE}
      - CI_REGISTRY_PASSWORD= ${CI_REGISTRY_PASSWORD}
      - CI_REGISTRY_USER= ${CI_REGISTRY_USER}
      - REACT_APP_EMAIL= ${REACT_APP_EMAIL}
      - REACT_APP_ID= ${REACT_APP_ID}
      - REACT_APP_PASSWORD= ${REACT_APP_PASSWORD}
      - REACT_APP_ID_REGEX=${REACT_APP_ID_REGEX}
      - REACT_APP_PLACE_REGEX= ${REACT_APP_PLACE_REGEX}
      - REACT_APP_SOCKETS= ${REACT_APP_SOCKETS}
      - REACT_APP_TOKEN= ${REACT_APP_TOKEN}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
