FROM node:8
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

ARG REACT_APP_LOG_LEVEL
ENV REACT_APP_LOG_LEVEL=$REACT_APP_LOG_LEVEL

ARG REACT_APP_ADDRESS
ENV REACT_APP_ADDRESS=$REACT_APP_ADDRESS

ARG REACT_APP_SOCKETS
ENV REACT_APP_SOCKETS=$REACT_APP_SOCKETS

ARG CI_REGISTRY
ENV CI_REGISTRY=$CI_REGISTRY

ARG CI_REGISTRY_IMAGE
ENV CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE

ARG CI_REGISTRY_PASSWORD
ENV CI_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD

ARG CI_REGISTRY_USER
ENV CI_REGISTRY_USER=$CI_REGISTRY_USER

ARG REACT_APP_EMAIL
ENV REACT_APP_EMAIL=$REACT_APP_EMAIL

ARG REACT_APP_ID
ENV REACT_APP_ID=$REACT_APP_ID

ARG REACT_APP_PASSWORD
ENV REACT_APP_PASSWORD=$REACT_APP_PASSWORD

ARG REACT_APP_ID_REGEX
ENV REACT_APP_ID_REGEX=$REACT_APP_ID_REGEX

ARG REACT_APP_PLACE_REGEX
ENV REACT_APP_PLACE_REGEX=$REACT_APP_PLACE_REGEX

ARG REACT_APP_TOKEN
ENV REACT_APP_TOKEN=$REACT_APP_TOKEN

EXPOSE 5000
RUN npm run build
RUN npm install -g serve
CMD [ "serve", "-s", "build" ]