FROM node:8
WORKDIR /app
COPY package.json /app
RUN yarn install
COPY . /app

ARG REACT_APP_ADRESS
ENV REACT_APP_ADRESS $REACT_APP_ADRESS

ARG CI_REGISTRY
ENV CI_REGISTRY $CI_REGISTRY

ARG CI_REGISTRY_IMAGE
ENV CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE

ARG CI_REGISTRY_PASSWORD
ENV CI_REGISTRY_PASSWORD $CI_REGISTRY_PASSWORD

ARG CI_REGISTRY_USER
ENV CI_REGISTRY_USER $CI_REGISTRY_USER

ARG REACT_APP_EMAIL
ENV REACT_APP_EMAIL $REACT_APP_EMAIL

ARG REACT_APP_ID
ENV REACT_APP_ID $REACT_APP_ID

ARG REACT_APP_PASSWORD
ENV REACT_APP_PASSWORD $REACT_APP_PASSWORD

ARG REACT_APP_ID_REGEX
ENV REACT_APP_ID_REGEX $REACT_APP_ID_REGEX

ARG REACT_APP_PLACE_REGEX
ENV REACT_APP_PLACE_REGEX $REACT_APP_PLACE_REGEX

ARG REACT_APP_SOCKETS
ENV REACT_APP_SOCKETS $REACT_APP_SOCKETS

ARG REACT_APP_TOKEN
ENV REACT_APP_TOKEN $REACT_APP_TOKEN

EXPOSE 5000
RUN yarn build
CMD [ "yarn", "run", "serve" ]